apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-stage
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/YOUR_USER/helm-repo.git
    targetRevision: main
    path: charts/demo-app
    helm:
      valueFiles:
        - ../../environments/stage/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
